=== Khmelov/JD2020-09-15/src/by/it/siarheikorbut/jd02_07/Person.dtd
<!ELEMENT Persons (Person)>
        <!ELEMENT Person (Email, NickName, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT NickName (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description, Brend, Model, CapasityEngine, CarBody)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Brend (#PCDATA)>
        <!ELEMENT Model (#PCDATA)>
        <!ELEMENT CapasityEngine (#PCDATA)>
        <!ELEMENT CarBody (#PCDATA)>

=== Khmelov/JD2020-09-15/src/by/it/siarheikorbut/jd02_07/Persons+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Persons SYSTEM "Person.dtd">
<Persons>
    <Person>
        <Email>myemail@it.by</Email>
        <NickName>MyNickName</NickName>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>новый автомобиль</Description>
                <Brend>Skoda</Brend>
                <Model>Rapid</Model>
                <CapasityEngine>1.6</CapasityEngine>
                <CarBody>лифтбэк</CarBody>
            </Ad>
            <Ad>
                <Description>старый автомобиль</Description>
                <Brend>Skoda</Brend>
                <Model>fabia</Model>
                <CapasityEngine>1.4</CapasityEngine>
                <CarBody>универсал</CarBody>
            </Ad>
        </Ads>
    </Person>
</Persons>
